site_name: auto-logger
site_author: duyixian
site_url: https://auto-logger.readthedocs.io
nav:
  - Home: 
    - 'Getting Started': user-guide/getting-started.md
    - 'Configuration Options': user-guide/configuration-options.md
  - About: about.md
theme: readthedocs
repo_url: https://github.com/duyixian1234/auto-logger/

